In [1]:
import pandas as pd
import numpy as np

In [12]:
df = pd.read_csv(r"c_elegans_data\maleChemicalAdjMatrix.csv")
df.head()

,Unnamed: 0,I1L,I1R,I2L,I2R,I3,I4,I5,I6,M1,...,vsrR,gonad,proctodeum,R1stR,R2stR,R3stL,R5stL,R7stL,R7stR,R9stL
0,I1L,NaN,NaN,10.0,NaN,3.0,NaN,2.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,I1R,NaN,NaN,NaN,6.0,1.0,NaN,2.0,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,I2L,2.0,NaN,NaN,3.0,NaN,13.0,2.0,2.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,I2R,NaN,1.0,3.0,NaN,NaN,20.0,2.0,3.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,I3,1.0,1.0,NaN,NaN,NaN,NaN,2.0,1.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
df.set_index(df.columns[0])

,I1L,I1R,I2L,I2R,I3,I4,I5,I6,M1,M2L,...,vsrR,gonad,proctodeum,R1stR,R2stR,R3stL,R5stL,R7stL,R7stR,R9stL
Unnamed: 0,,,,,,,,,,,,,,,,,,,,,
I1L,NaN,NaN,10.0,NaN,3.0,NaN,2.0,1.0,NaN,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
I1R,NaN,NaN,NaN,6.0,1.0,NaN,2.0,NaN,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
I2L,2.0,NaN,NaN,3.0,NaN,13.0,2.0,2.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
I2R,NaN,1.0,3.0,NaN,NaN,20.0,2.0,3.0,3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
I3,1.0,1.0,NaN,NaN,NaN,NaN,2.0,1.0,2.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
CP05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,46.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CP06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,43.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CP07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CP08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CP09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
import json
with open(r"c_elegans_data\neuron_indices.json", "r") as file:
    data = dict(json.load(file))